"""Enumeration types for the Perpetua Flow backend.

T059: All enums for database models and API schemas.
Per data-model.md and api-specification.md.
"""

from enum import Enum


# ============================================================================
# User & Authentication Enums
# ============================================================================


class UserTier(str, Enum):
    """User subscription tier."""

    FREE = "free"
    PRO = "pro"


# ============================================================================
# Task Enums
# ============================================================================


class TaskPriority(str, Enum):
    """Task priority levels (FR-007)."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class CompletedBy(str, Enum):
    """How a task was completed (FR-008, FR-009, FR-010)."""

    MANUAL = "manual"  # User marked complete
    AUTO = "auto"  # Auto-completed when all subtasks done
    FORCE = "force"  # Force-completed by user


# ============================================================================
# Subtask Enums
# ============================================================================


class SubtaskSource(str, Enum):
    """Source of subtask creation (FR-021)."""

    USER = "user"  # Created by user
    AI = "ai"  # Generated by AI


# ============================================================================
# Note Enums
# ============================================================================


class TranscriptionStatus(str, Enum):
    """Voice transcription status for notes."""

    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"


# ============================================================================
# Reminder Enums
# ============================================================================


class ReminderType(str, Enum):
    """Reminder timing type (FR-025)."""

    BEFORE = "before"  # Minutes before due date
    AFTER = "after"  # Minutes after due date
    ABSOLUTE = "absolute"  # Specific time


class NotificationMethod(str, Enum):
    """Notification delivery method (FR-028)."""

    PUSH = "push"
    IN_APP = "in_app"


# ============================================================================
# Achievement Enums
# ============================================================================


class AchievementCategory(str, Enum):
    """Achievement categories."""

    TASKS = "tasks"
    STREAKS = "streaks"
    FOCUS = "focus"
    NOTES = "notes"


class PerkType(str, Enum):
    """Types of perks granted by achievements (FR-046)."""

    MAX_TASKS = "max_tasks"
    MAX_NOTES = "max_notes"
    DAILY_CREDITS = "daily_credits"


# ============================================================================
# Credit Enums
# ============================================================================


class CreditType(str, Enum):
    """AI credit source type (FR-042)."""

    KICKSTART = "kickstart"  # One-time new user credits
    DAILY = "daily"  # Daily Pro credits (expire at UTC 00:00)
    SUBSCRIPTION = "subscription"  # Monthly Pro credits (carry over up to 50)
    PURCHASED = "purchased"  # Bought credits (never expire)


class CreditOperation(str, Enum):
    """Credit transaction operation type."""

    GRANT = "grant"  # Credits added
    CONSUME = "consume"  # Credits used
    EXPIRE = "expire"  # Credits expired
    CARRYOVER = "carryover"  # Subscription credits carried over


# ============================================================================
# Subscription Enums
# ============================================================================


class SubscriptionStatus(str, Enum):
    """Subscription payment/status states (FR-049)."""

    ACTIVE = "active"  # Payment current, Pro tier active
    PAST_DUE = "past_due"  # Payment failed, retrying
    GRACE = "grace"  # 3 failures, grace period active
    CANCELLED = "cancelled"  # User cancelled, active until period end
    EXPIRED = "expired"  # Grace expired, downgraded to free


# ============================================================================
# Activity Log Enums
# ============================================================================


class EntityType(str, Enum):
    """Types of entities tracked in activity logs (FR-052)."""

    TASK = "task"
    SUBTASK = "subtask"
    NOTE = "note"
    REMINDER = "reminder"
    SUBSCRIPTION = "subscription"
    ACHIEVEMENT = "achievement"
    AI_CHAT = "ai_chat"


class ActivitySource(str, Enum):
    """Who initiated an action (FR-054)."""

    USER = "user"  # User action
    AI = "ai"  # AI-initiated (with confirmation)
    SYSTEM = "system"  # System job or automation


# ============================================================================
# Notification Enums
# ============================================================================


class NotificationType(str, Enum):
    """Types of notifications."""

    REMINDER = "reminder"  # Task reminder
    ACHIEVEMENT = "achievement"  # Achievement unlocked
    SUBSCRIPTION = "subscription"  # Subscription status change
    SYSTEM = "system"  # System notification


# ============================================================================
# Job Queue Enums
# ============================================================================


class JobStatus(str, Enum):
    """Background job status."""

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    DEAD = "dead"  # Exceeded max retries


class JobType(str, Enum):
    """Background job types (per plan.md)."""

    REMINDER_FIRE = "reminder_fire"
    STREAK_CALCULATE = "streak_calculate"
    CREDIT_EXPIRE = "credit_expire"
    SUBSCRIPTION_CHECK = "subscription_check"
    RECURRING_TASK_GENERATE = "recurring_task_generate"


# ============================================================================
# Tombstone Enums
# ============================================================================


class TombstoneEntityType(str, Enum):
    """Entity types that can be recovered (FR-062)."""

    TASK = "task"
    NOTE = "note"
